### ISSUE TITLE
All tests fail

### ISSUE THREAD

**Issue by nadim7** [jGleitz/JUnit-KIT#112]
When I start the final1-JUnit4-tests, all of them just fail.

Stack Trace of the first sub test:

```
java.lang.ExceptionInInitializerError
    at test.framework.Terminal.<clinit>(Terminal.java:98)
    at test.TestObject.run(TestObject.java:641)
    at test.TestObject.runStaticVoid(TestObject.java:468)
    at test.TestObject.runStaticVoid(TestObject.java:481)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:222)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:202)
    at final1.subtests.InvalidCommandLineArgumentsTest.noSuchFileTest(InvalidCommandLineArgumentsTest.java:44)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
Caused by: java.lang.NullPointerException
    at java.util.Objects.requireNonNull(Unknown Source)
    at java.util.Arrays$ArrayList.<init>(Unknown Source)
    at java.util.Arrays.asList(Unknown Source)
    at test.mocking.MockCompiler.getJavaCompiler(MockCompiler.java:147)
    at test.mocking.MockCompiler.<clinit>(MockCompiler.java:33)
    ... 17 more
```

Stack Trace of the other tests (as following or near to that):

```
java.lang.NoClassDefFoundError: Could not initialize class test.framework.Terminal
    at test.TestObject.run(TestObject.java:641)
    at test.TestObject.runStaticVoid(TestObject.java:468)
    at test.TestObject.runStaticVoid(TestObject.java:481)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:222)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:202)
    at final1.subtests.InvalidCommandLineArgumentsTest.noArgumentTest(InvalidCommandLineArgumentsTest.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

OS: Windows7 Professional 64bit (SP1)
JRE: 1.8.0_25
used Compliance Level: 1.7
used Execution Environment: JavaSE-1.7

**Comment by jGleitz** [comment]
> JRE: 1.8.0_25

Do you have a JDK installed?

**Comment by nadim7** [comment]
Yes, it's the JDK version 8u40 (64-bit)

**Comment by jGleitz** [comment]
Please try again with 3d67791 (it's already in the ownCloud). The line the `NullPointerException` was thrown at did not belong there at all. Removing it might fix the issue.

**Comment by nadim7** [comment]
Thanks, this solved the problem
