### ISSUE TITLE
TestObject$TestClassLoader may have problems with nested exception classes

### ISSUE THREAD

**Issue by pcworld** [jGleitz/JUnit-KIT#31]
May be a configuration issue on my end, I'm not sure.

e.g.

```
java.lang.AssertionError: An Exception occurred while running main([0.3, e7767e81-14b6-4075-9f5c-e7aaa8d25e24.txt]): 

java.lang.LinkageError: loader constraint violation: when resolving method "edu.kit.informatik.bookDB.BookDatabaseCLI$InvalidFileFormatException.<init>(Ledu/kit/informatik/bookDB/BookDatabaseCLI;Ljava/lang/String;)V" the class loader (instance of test/TestObject$TestClassLoader) of the current class, edu/kit/informatik/bookDB/BookDatabaseCLI, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for resolved class, edu/kit/informatik/bookDB/BookDatabaseCLI$InvalidFileFormatException, have different Class objects for the type tabaseCLI$InvalidFileFormatException.<init>(Ledu/kit/informatik/bookDB/BookDatabaseCLI;Ljava/lang/String;)V used in the signature
    at edu.kit.informatik.bookDB.BookDatabaseCLI.readBook(BookDatabaseCLI.java:104)
    at edu.kit.informatik.bookDB.BookDatabaseCLI.<init>(BookDatabaseCLI.java:50)
    at edu.kit.informatik.bookDB.BookDatabaseCLI.main(BookDatabaseCLI.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at test.TestObject.run(TestObject.java:596)
    at test.TestObject.runStaticVoid(TestObject.java:424)
    at test.TestObject.runStaticVoid(TestObject.java:437)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:287)
    at sheet6.c_bookDatabase.subtests.InputFileParsingTest.testWrongInputFileAttributeValues(InputFileParsingTest.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)

    at org.junit.Assert.fail(Assert.java:88)
    at test.TestObject.run(TestObject.java:649)
    at test.TestObject.runStaticVoid(TestObject.java:424)
    at test.TestObject.runStaticVoid(TestObject.java:437)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:287)
    at sheet6.c_bookDatabase.subtests.InputFileParsingTest.testWrongInputFileAttributeValues(InputFileParsingTest.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

and

```
java.lang.AssertionError: An Exception occurred while running main([0.3, 489b96e3-1537-4f9b-8f15-74170eb5a0dd.txt]): 

java.lang.IllegalAccessError: tried to access class edu.kit.informatik.bookDB.SearchQueryParser$ParseException from class edu.kit.informatik.bookDB.BookDatabaseCLI
    at edu.kit.informatik.bookDB.BookDatabaseCLI.interactiveCLI(BookDatabaseCLI.java:135)
    at edu.kit.informatik.bookDB.BookDatabaseCLI.<init>(BookDatabaseCLI.java:61)
    at edu.kit.informatik.bookDB.BookDatabaseCLI.main(BookDatabaseCLI.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at test.TestObject.run(TestObject.java:596)
    at test.TestObject.runStaticVoid(TestObject.java:424)
    at test.TestObject.runStaticVoid(TestObject.java:437)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:287)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:305)
    at sheet6.c_bookDatabase.subtests.SearchTermParsingTest.testIllegalSearchTerms(SearchTermParsingTest.java:128)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)

    at org.junit.Assert.fail(Assert.java:88)
    at test.TestObject.run(TestObject.java:649)
    at test.TestObject.runStaticVoid(TestObject.java:424)
    at test.TestObject.runStaticVoid(TestObject.java:437)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:287)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:305)
    at sheet6.c_bookDatabase.subtests.SearchTermParsingTest.testIllegalSearchTerms(SearchTermParsingTest.java:128)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

**Comment by jGleitz** [comment]
Puh.... I started to look up this error and found only documents calling it _very_ nasty... I have never used class loaders before, therefore I'll need to investigate.
Are you able to post a version of your class that would not be a solution to the task sheet but still produces this error? It would be very helpful to be able to reproduce this on my own machine.

**Comment by pcworld** [comment]
A simple class that leads to an IllegalAccessError:

```
package edu.kit.informatik.bookDBtest;

public class BookDatabaseCLI {

    public static void main(String[] args) {
        new BookDatabaseCLI();
    }

    public BookDatabaseCLI() {
        try {
            throw new NonPublicException();
        } catch (NonPublicException e) {
        }
    }

    class NonPublicException extends Exception {
        private static final long serialVersionUID = 1L;
    }

}
```

=>

```
java.lang.AssertionError: An Exception occurred while running main([, c6077e89-6661-4f2d-ab46-f8cf20297990.txt]): 

java.lang.IllegalAccessError: edu/kit/informatik/bookDBtest/NonPublicException
    at edu.kit.informatik.bookDBtest.BookDatabaseCLI.<init>(BookDatabaseCLI.java:11)
    at edu.kit.informatik.bookDBtest.BookDatabaseCLI.main(BookDatabaseCLI.java:6)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at test.TestObject.run(TestObject.java:596)
    at test.TestObject.runStaticVoid(TestObject.java:424)
    at test.TestObject.runStaticVoid(TestObject.java:437)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:287)
    at sheet6.c_bookDatabase.subtests.CommandLineArgumentsTest.testWrongTolerance(CommandLineArgumentsTest.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)

    at org.junit.Assert.fail(Assert.java:88)
    at test.TestObject.run(TestObject.java:649)
    at test.TestObject.runStaticVoid(TestObject.java:424)
    at test.TestObject.runStaticVoid(TestObject.java:437)
    at test.InteractiveConsoleTest.errorTest(InteractiveConsoleTest.java:287)
    at sheet6.c_bookDatabase.subtests.CommandLineArgumentsTest.testWrongTolerance(CommandLineArgumentsTest.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

Note that it doesn't necessarily have to be a nested Exception class, if NonPublicException is in its own file but not marked `public` it will lead to the same IllegalAccessError.
I haven't yet found a simple test case for the `LinkageError: loader constraint violation` error but I guess the above test case should suffice for the moment.

**Comment by jGleitz** [comment]
The `IllegalAccessError` is because the nested class gets loaded by another class loader than the outer one does. Therefore its in another Java runtime package. As not being declared public, the access is indeed illegal.
Just a side note. I'm working on a fix but can't promise anything.

**Comment by jGleitz** [comment]
@pcworld: 322f5d12a8f84788d8b9462d6beb869ff8175b7b should contain a fix for the `IllegalAccessError`. Can you please confirm?
Does that solve the `LinkageError`, too? (I expect it to).

**Comment by pcworld** [comment]
That commit seems to have introduced the following regression:
Consider the following class for sheet6:

``` java
package edu.kit.informatik.bookDBtest;

import edu.kit.informatik.Terminal;

public class BookDatabaseCLI {

    public static void main(String[] args) {
        Terminal.readLine();
    }

}
```

Lots of tests fail with a timeout, e.g.:

<pre>sheet6.c_bookDatabase.subtests.BasicCommandsTest
testQuit(sheet6.c_bookDatabase.subtests.BasicCommandsTest)
java.lang.Exception: test timed out after 5000 milliseconds
    at java.io.BufferedInputStream.read(BufferedInputStream.java:325)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:154)
    at java.io.BufferedReader.readLine(BufferedReader.java:317)
    at java.io.BufferedReader.readLine(BufferedReader.java:382)
    at edu.kit.informatik.Terminal.readLine(Terminal.java:53)
    at edu.kit.informatik.bookDBtest.BookDatabaseCLI.main(BookDatabaseCLI.java:8)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at test.TestObject.run(TestObject.java:597)
    at test.TestObject.runStaticVoid(TestObject.java:425)
    at test.TestObject.runStaticVoid(TestObject.java:438)
    at test.InteractiveConsoleTest.oneLineTest(InteractiveConsoleTest.java:131)
    at test.InteractiveConsoleTest.oneLineTest(InteractiveConsoleTest.java:95)
    at sheet6.c_bookDatabase.subtests.BasicCommandsTest.testQuit(BasicCommandsTest.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)</pre>

That didn't happen in a2de08b4ef5a0178f7e87f445267189f0c9c1778.

**Comment by jGleitz** [comment]
That's right @RomanLan reported that, too. I rolled back to a2de08b4ef5a0178f7e87f445267189f0c9c1778. 
I'm currently reworking essential parts of the framework. As soon as this is done, I will hopefully be able to introduce the fix regression-free.

**Comment by jGleitz** [comment]
#32 (76f4cbc7a9fac82c6795f5263585b60d77d3a6aa) contains said fix again. _Please test_!

**Comment by pcworld** [comment]
It works on the development branch.

**Comment by jGleitz** [comment]
@pcworld So both the `IllegalAccessError` and `LinkageError` are fixed?

**Comment by pcworld** [comment]
> So both the IllegalAccessError and LinkageError are fixed?

Yes.

**Comment by jGleitz** [comment]
Nice.
@pcworld: Did you feel a serious performance hit while testing development branch (Or any other issues)? Please comment on #32.
