### ISSUE TITLE
Probably a problem with new line in output

### ISSUE THREAD

**Issue by rapus95** [jGleitz/JUnit-KIT#4]
Got same error in "CitiesInteractiveConsoleTest": Tests: "searchNull", "insertSearchTest"

When executing the test with my tree the result fails, because at the end of my output line there is a "\r" new line code. Put since we shall print to console we can't prevent that because we have to use the Terminal.printline method which automatically makes a new line...

Thus my question: Is there a way to fix this? Is it a problem (of the Tasks perspective)? or do i have to ignore it?

Here is the actual message/StackTrace:

java.lang.AssertionError: We ran a session on your interactive consolethat has been called with the command line arguments [traverse=pre-order], running the commands 

insert Pfaffenhofen:1
insert Waldstadt:3
search Freudenstadt
insert Freudenstadt:66
search Freudenstadt
quit

 but got unexpected output:
Expected was:

is "Freudenstadt:null"
is "Freudenstadt:66"

Your output was:

Freudenstadt:null
Freudenstadt:66

First error at line 1:
Expected: is "Freudenstadt:null"
     but: was "Freudenstadt:null\r"
    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
    at org.junit.Assert.assertThat(Assert.java:865)
    at test.InteractiveConsoleTest.multiLineTest(InteractiveConsoleTest.java:148)
    at test.InteractiveConsoleTest.multiLineTest(InteractiveConsoleTest.java:209)
    at sheet5.b_cities.CitiesInteracitveConsoleTest.searchNull(CitiesInteracitveConsoleTest.java:248)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by jGleitz** [comment]
How old is your copy of the code? This was a bug that I fixed this afternoon (at least I thought so).

**Comment by rapus95** [comment]
ok in that case... mine was older :)

but got another one now, opening a new issue
