### ISSUE TITLE
IllegalArgumentException thrown by definePackage() in loadClass()

### ISSUE THREAD

**Issue by MartinLoeper** [jGleitz/JUnit-KIT#6]
Die Ausführung der Tests schlägt ab dem ersten Aufruf zu ´resetClass()´ fehl.
Ich musste bei mir den Quellcode von TestObject.java wie folgt ergänzen, damit er wie erwartet lauffähig wird:

``` Java
        private Class<?> loadClass() {
            try {
                definePackage(className.substring(0, className.lastIndexOf(".")), "", "", "", "", "", "", null);
            }
            catch(IllegalArgumentException e) {
                // why does this happen after the first test succeeded?
            }
            return defineClass(className, classData, 0, classData.length);
        }
```

Ist dies ein Bug, der auf eine bestimmte Java-Komponente (JDK8?) zurückzuführen ist oder habe ich etwas falsch eingebunden?

---

Eclipse: 4.4.0 (Build id: 20140612-0600)
Java: 1.8.0_25 (ich weiß, nicht das 7er...)
JUnit: 4

**Comment by jGleitz** [comment]
Hm, der Bug überrascht mich. Der betroffene Code is aber recht neu. Folgende Informationen wären hilfreich:
- Was ist die genaue Fehlermeldung der `IlleagalArgumentException`?
- Wie genau hast du den Klassenamen in den JVM-Argumenten gesetzt?

**Comment by MartinLoeper** [comment]
Der Stack-Trace lautet wie folgt:

```
java.lang.IllegalArgumentException: edu.kit.informatik
    at java.lang.ClassLoader.definePackage(Unknown Source)
    at test.TestObject$TestClassLoader.loadClass(TestObject.java:1130)
    at test.TestObject$TestClassLoader.access$1(TestObject.java:1128)
    at test.TestObject.resetClass(TestObject.java:343)
    at test.InteractiveConsoleTest.oneLineTest(InteractiveConsoleTest.java:120)
    at test.InteractiveConsoleTest.oneLineTest(InteractiveConsoleTest.java:86)
    at sheet6.a_books.BooksInteractiveConsoleTest.search1(BooksInteractiveConsoleTest.java:150)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Das ist leider keine wirklich aussagekräftige Fehlermeldung... Ein Hinweis gibt jedoch das Javadoc dazu...:
"If package name duplicates an existing package either in this class loader or one of its ancestors".

Den Klassenname habe ich wie folgt gesetzt: <em>edu.kit.informatik.MainClass</em>, wobei MainClass die main-Methode enthält und im Package edu.kit.informatik liegt.

**Comment by jGleitz** [comment]
Hm, daran habe ich nicht gedacht. a570d701e99f3e0bf3bc2b30d0bcb49eef00d331 sollte den Bug beheben. Kannst du das überprüfen und rückmelden?

**Comment by MartinLoeper** [comment]
Der Bug ist für meine Konfiguration mit a570d701e99f3e0bf3bc2b30d0bcb49eef00d331 nun vollständig gefixt.
